// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Money.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ETF 歷史回測比較")]
    public partial class ETF歷史回測比較Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Backtest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "Features", "ETF 歷史回測比較", "  作為投資者\r\n  我想要比較台股與美股 ETF 的歷史績效\r\n  為了做出更好的投資決策", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ETF 回測頁面存在")]
        [NUnit.Framework.CategoryAttribute("WalkingSkeleton")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        public void ETF回測頁面存在()
        {
            string[] tagsOfScenario = new string[] {
                    "WalkingSkeleton",
                    "Backtest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ETF 回測頁面存在", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 12
    testRunner.Then("頁面應該載入成功", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 13
    testRunner.And("頁面標題應該包含 \"ETF 歷史回測\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ETF 選擇介面")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("ETFSelection")]
        public void ETF選擇介面()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "ETFSelection"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ETF 選擇介面", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 20
    testRunner.Then("我應該看到 ETF 選擇區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 21
    testRunner.And("應該有 ETF 搜尋框", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 22
    testRunner.And("預設選擇 \"0050\" 與 \"VTI\" 兩檔 ETF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("可搜尋的 ETF 下拉選單")]
        [NUnit.Framework.CategoryAttribute("skip")]
        [NUnit.Framework.CategoryAttribute("SearchableDropdown")]
        public void 可搜尋的ETF下拉選單()
        {
            string[] tagsOfScenario = new string[] {
                    "skip",
                    "SearchableDropdown"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("可搜尋的 ETF 下拉選單", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
    testRunner.Given("我點擊 ETF 搜尋框", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 27
    testRunner.Then("應該顯示可搜尋的下拉選單", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 28
    testRunner.And("輸入時即時顯示符合的選項", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("支援的 ETF 清單")]
        [NUnit.Framework.CategoryAttribute("skip")]
        [NUnit.Framework.CategoryAttribute("ETFList")]
        public void 支援的ETF清單()
        {
            string[] tagsOfScenario = new string[] {
                    "skip",
                    "ETFList"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("支援的 ETF 清單", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Then("台股 ETF 應該包含 \"0050\", \"0056\", \"006208\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 33
    testRunner.And("美股 ETF 應該包含 \"VTI\", \"VOO\", \"VT\", \"QQQ\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("回測參數設定")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("BacktestParams")]
        public void 回測參數設定()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "BacktestParams"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("回測參數設定", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 39
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 40
    testRunner.Then("我應該看到回測參數設定區", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 41
    testRunner.And("應該可以選擇回測期間", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 42
    testRunner.And("應該可以選擇投資方式", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 43
    testRunner.And("應該有開始回測按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("後端抓取 ETF 歷史資料")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("DataFetch")]
        public void 後端抓取ETF歷史資料()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "DataFetch"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("後端抓取 ETF 歷史資料", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 49
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 50
    testRunner.When("點擊開始回測按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
#line 51
    testRunner.Then("回測完成後應該顯示結果區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("績效走勢圖顯示")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("Chart")]
        public void 績效走勢圖顯示()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "Chart"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("績效走勢圖顯示", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 58
    testRunner.When("點擊開始回測按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
#line 59
    testRunner.Then("回測完成後應該顯示結果區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 60
    testRunner.And("應該顯示績效走勢圖", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("投資組合模式切換")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("Portfolio")]
        public void 投資組合模式切換()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "Portfolio"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("投資組合模式切換", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 66
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 67
    testRunner.Then("應該有回測模式切換選項", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 68
    testRunner.And("可以切換到投資組合模式", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("回測結果匯出")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("Export")]
        public void 回測結果匯出()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "Export"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("回測結果匯出", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 74
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 75
    testRunner.When("點擊開始回測按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
#line 76
    testRunner.Then("回測完成後應該顯示結果區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 77
    testRunner.And("應該有分享按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("投資組合進階風險指標")]
        [NUnit.Framework.CategoryAttribute("Backtest")]
        [NUnit.Framework.CategoryAttribute("PortfolioRiskMetrics")]
        public void 投資組合進階風險指標()
        {
            string[] tagsOfScenario = new string[] {
                    "Backtest",
                    "PortfolioRiskMetrics"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("投資組合進階風險指標", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 83
    testRunner.Given("我開啟瀏覽器進入 ETF 回測頁面 \"/calculator/backtest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 84
    testRunner.When("切換到投資組合模式", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "當");
#line hidden
#line 85
    testRunner.And("點擊開始回測按鈕", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 86
    testRunner.Then("應該顯示投資組合風險指標區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 87
    testRunner.And("應該顯示組合與個別ETF比較表", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 88
    testRunner.And("組合的年化報酬率應該有數值", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 89
    testRunner.And("組合的夏普比率應該有數值", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
#line 90
    testRunner.And("風險指標旁邊應該有解釋圖示", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "而且");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
