// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Money.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("首頁導覽")]
    public partial class 首頁導覽Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "HomePage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("zh-TW"), "Features", "首頁導覽", "  作為投資新手\r\n  我想要一個專業且友善的首頁\r\n  為了快速了解網站功能並開始使用", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("首頁 Hero 區塊顯示")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("Hero")]
        public void 首頁Hero區塊顯示()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "Hero"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("首頁 Hero 區塊顯示", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "元素",
                            "內容"});
                table1.AddRow(new string[] {
                            "主標題",
                            "讓投資變得簡單"});
                table1.AddRow(new string[] {
                            "副標題",
                            "被動指數投資，穩健累積財富"});
                table1.AddRow(new string[] {
                            "CTA 按鈕",
                            "開始計算"});
#line 10
    testRunner.Then("我應該看到 Hero 區塊包含:", ((string)(null)), table1, "那麼");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("功能卡片快速入口")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("FeatureCards")]
        public void 功能卡片快速入口()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "FeatureCards"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("功能卡片快速入口", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "卡片標題",
                            "圖示",
                            "連結"});
                table2.AddRow(new string[] {
                            "複利計算機",
                            "🧮",
                            "/calculator/dca"});
                table2.AddRow(new string[] {
                            "退休金計算",
                            "🔥",
                            "/calculator/fire"});
#line 19
    testRunner.Then("功能卡片區應該顯示 2 張卡片:", ((string)(null)), table2, "那麼");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("周冠男教授名言區塊")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("ProfessorQuotes")]
        public void 周冠男教授名言區塊()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "ProfessorQuotes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("周冠男教授名言區塊", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 27
    testRunner.Then("我應該看到 \"投資智慧語錄\" 區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 28
    testRunner.And("區塊標題顯示 \"周冠男教授名言\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line hidden
#line 29
    testRunner.And("顯示至少 1 則名言內容", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("頁尾資訊顯示")]
        [NUnit.Framework.CategoryAttribute("Footer")]
        public void 頁尾資訊顯示()
        {
            string[] tagsOfScenario = new string[] {
                    "Footer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("頁尾資訊顯示", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "項目",
                            "內容"});
                table3.AddRow(new string[] {
                            "免責聲明",
                            "本網站僅供參考，不構成投資建議"});
                table3.AddRow(new string[] {
                            "版權聲明",
                            "被動投資計算機"});
#line 34
    testRunner.Then("頁面底部顯示 Footer 包含:", ((string)(null)), table3, "那麼");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("為什麼選擇被動投資區塊")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("WhyPassive")]
        public void 為什麼選擇被動投資區塊()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "WhyPassive"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("為什麼選擇被動投資區塊", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 41
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 42
    testRunner.Then("我應該看到 \"為什麼選擇被動投資\" 區塊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "數據",
                            "說明"});
                table4.AddRow(new string[] {
                            "90%",
                            "主動基金長期跑輸指數"});
                table4.AddRow(new string[] {
                            "0.03%",
                            "指數基金超低費用率"});
                table4.AddRow(new string[] {
                            "20 年",
                            "長期投資複利效果驚人"});
#line 43
    testRunner.And("區塊內包含至少 3 個統計數據:", ((string)(null)), table4, "並且");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("導覽列功能")]
        [NUnit.Framework.CategoryAttribute("Navigation")]
        [NUnit.Framework.CategoryAttribute("Header")]
        public void 導覽列功能()
        {
            string[] tagsOfScenario = new string[] {
                    "Navigation",
                    "Header"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("導覽列功能", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 51
    testRunner.Given("我開啟瀏覽器進入首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "項目",
                            "連結"});
                table5.AddRow(new string[] {
                            "Logo",
                            "/"});
                table5.AddRow(new string[] {
                            "計算工具",
                            "/calculator"});
#line 52
    testRunner.Then("頁面頂部顯示導覽列包含:", ((string)(null)), table5, "那麼");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("手機版首頁響應式設計")]
        [NUnit.Framework.CategoryAttribute("RWD")]
        [NUnit.Framework.CategoryAttribute("Mobile")]
        public void 手機版首頁響應式設計()
        {
            string[] tagsOfScenario = new string[] {
                    "RWD",
                    "Mobile"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("手機版首頁響應式設計", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 59
    testRunner.Given("我用手機尺寸 375x667 瀏覽首頁 \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "假設");
#line hidden
#line 60
    testRunner.Then("導覽列顯示漢堡選單圖示", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "那麼");
#line hidden
#line 61
    testRunner.And("頁面無橫向捲軸", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "並且");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
